listen = ":1323"
phase = "local"

sqliteDBPath = "./gorm.db"
jwtSigningKey = "jwtkey"

# db sqlite, postgre
db ="postgre"

[postgre]
ip = "127.0.0.1"
port = "5432"
dbname = "postgres"
user = "postgres"
password = "echogorm"
sslmode = "disable"
timeZone = "Asia/Seoul"
